/*
select ((ROW_NUMBER() OVER(ORDER BY LocalidadId ASC))+500)    id,
       '"UNKNOW"'                                             usuarioalta,
       '"UNKNOW"'                                             usuarioumod,
       '"LOCALIDAD"'                                          clase,
       '"'+replace(LocalidadDesc, '.............', '')+'"'    nombre,
       LocalidadId                                            orden,
       10                                                     tipo,
       ProvinciaId                                            valorint,
       (case LocalidadId when 4 then 'true' else 'false' end) valorbol,
       1                                                      version
  from Localidades
*/

--------------------------------------------------------------------------------------------------------
--------------------------------------------------------------------------------------------------------
-- VALORES A TENER EN CUENTA:                                                                         --
-- orden: es el id origen                                                                             --
-- valorint: define a que Provincia pertenece la csselects                                            --
-- valorbol: define si la csselects es LOCAL (true) o VISITANTE (false) para calcular Cargos          --
--------------------------------------------------------------------------------------------------------
--------------------------------------------------------------------------------------------------------
INSERT INTO parametro (id, usuarioalta, usuarioumod, clase, nombre, orden, tipo, valorint, valorbol, version)
VALUES (501, 'UNKNOW', 'UNKNOW', 'LOCALIDAD', 'POSADAS', 4, 10, 3, true, 1), 
       (502, 'UNKNOW', 'UNKNOW', 'LOCALIDAD', 'AVELLANEDA', 5, 10, 1, false, 1), 
       (503, 'UNKNOW', 'UNKNOW', 'LOCALIDAD', 'ROSARIO', 6, 10, 15, false, 1), 
       (504, 'UNKNOW', 'UNKNOW', 'LOCALIDAD', 'CAPITAL FEDERAL', 7, 10, 2, false, 1), 
       (505, 'UNKNOW', 'UNKNOW', 'LOCALIDAD', 'CORRIENTES', 8, 10, 4, false, 1), 
       (506, 'UNKNOW', 'UNKNOW', 'LOCALIDAD', 'REMEDIOS DE ESCALADA', 9, 10, 1, false, 1), 
       (507, 'UNKNOW', 'UNKNOW', 'LOCALIDAD', 'LUJAN', 10, 10, 1, false, 1), 
       (508, 'UNKNOW', 'UNKNOW', 'LOCALIDAD', 'MORON', 11, 10, 1, false, 1), 
       (509, 'UNKNOW', 'UNKNOW', 'LOCALIDAD', 'ASUNCION', 12, 10, 3, false, 1), 
       (510, 'UNKNOW', 'UNKNOW', 'LOCALIDAD', 'RESISTENCIA', 13, 10, 10, false, 1), 
       (511, 'UNKNOW', 'UNKNOW', 'LOCALIDAD', 'CORDOBA', 14, 10, 14, false, 1), 
       (512, 'UNKNOW', 'UNKNOW', 'LOCALIDAD', 'LEANDRO N. ALEM', 15, 10, 3, false, 1), 
       (513, 'UNKNOW', 'UNKNOW', 'LOCALIDAD', 'GARUPA', 16, 10, 3, false, 1), 
       (514, 'UNKNOW', 'UNKNOW', 'LOCALIDAD', 'CANDELARIA', 17, 10, 3, false, 1), 
       (515, 'UNKNOW', 'UNKNOW', 'LOCALIDAD', 'SANTA ANA', 18, 10, 3, false, 1), 
       (516, 'UNKNOW', 'UNKNOW', 'LOCALIDAD', 'CAMPO GRANDE', 19, 10, 3, false, 1), 
       (517, 'UNKNOW', 'UNKNOW', 'LOCALIDAD', 'SALTO ENCANTADO', 20, 10, 17, false, 1), 
       (518, 'UNKNOW', 'UNKNOW', 'LOCALIDAD', '25 DE MAYO', 21, 10, 3, false, 1), 
       (519, 'UNKNOW', 'UNKNOW', 'LOCALIDAD', 'EL SOBERBIO', 22, 10, 3, false, 1), 
       (520, 'UNKNOW', 'UNKNOW', 'LOCALIDAD', 'SAN PEDRO', 23, 10, 3, false, 1), 
       (521, 'UNKNOW', 'UNKNOW', 'LOCALIDAD', 'APOSTOLES', 24, 10, 3, false, 1), 
       (522, 'UNKNOW', 'UNKNOW', 'LOCALIDAD', 'SAN JOSE', 25, 10, 3, false, 1), 
       (523, 'UNKNOW', 'UNKNOW', 'LOCALIDAD', 'SAN JAVIER', 26, 10, 3, false, 1), 
       (524, 'UNKNOW', 'UNKNOW', 'LOCALIDAD', 'CONCEPCION', 27, 10, 3, false, 1), 
       (525, 'UNKNOW', 'UNKNOW', 'LOCALIDAD', 'CERRO AZUL', 28, 10, 3, false, 1), 
       (526, 'UNKNOW', 'UNKNOW', 'LOCALIDAD', 'SAN CARLOS', 29, 10, 4, false, 1), 
       (527, 'UNKNOW', 'UNKNOW', 'LOCALIDAD', 'SAN IGNACIO', 30, 10, 3, false, 1), 
       (528, 'UNKNOW', 'UNKNOW', 'LOCALIDAD', 'SANTO PIPO', 31, 10, 3, false, 1), 
       (529, 'UNKNOW', 'UNKNOW', 'LOCALIDAD', 'CAPIOVI', 32, 10, 3, false, 1), 
       (530, 'UNKNOW', 'UNKNOW', 'LOCALIDAD', 'GARUHAPE', 33, 10, 3, false, 1), 
       (531, 'UNKNOW', 'UNKNOW', 'LOCALIDAD', 'RUIZ DE MONTOYA', 34, 10, 3, false, 1), 
       (532, 'UNKNOW', 'UNKNOW', 'LOCALIDAD', 'EL ALCAZAR', 35, 10, 3, false, 1), 
       (533, 'UNKNOW', 'UNKNOW', 'LOCALIDAD', 'BERNARDO  IRIGOYEN', 36, 10, 3, false, 1), 
       (534, 'UNKNOW', 'UNKNOW', 'LOCALIDAD', 'SAN ANTONIO', 37, 10, 3, false, 1), 
       (535, 'UNKNOW', 'UNKNOW', 'LOCALIDAD', 'PUERTO ESPERANZA', 38, 10, 3, false, 1), 
       (536, 'UNKNOW', 'UNKNOW', 'LOCALIDAD', 'WANDA', 39, 10, 3, false, 1), 
       (537, 'UNKNOW', 'UNKNOW', 'LOCALIDAD', 'PUERTO LIBERTAD', 40, 10, 3, false, 1), 
       (538, 'UNKNOW', 'UNKNOW', 'LOCALIDAD', 'PUERTO IGUAZU', 41, 10, 3, false, 1), 
       (539, 'UNKNOW', 'UNKNOW', 'LOCALIDAD', 'OBERA', 42, 10, 3, false, 1), 
       (540, 'UNKNOW', 'UNKNOW', 'LOCALIDAD', 'DOS DE MAYO', 43, 10, 3, false, 1), 
       (541, 'UNKNOW', 'UNKNOW', 'LOCALIDAD', 'ARISTOBULO DEL VALLE', 44, 10, 3, false, 1),
       (542, 'UNKNOW', 'UNKNOW', 'LOCALIDAD', 'SAN VICENTE', 45, 10, 3, false, 1), 
       (543, 'UNKNOW', 'UNKNOW', 'LOCALIDAD', 'GOBERNADOR ROCA', 46, 10, 3, false, 1), 
       (544, 'UNKNOW', 'UNKNOW', 'LOCALIDAD', 'JARDIN  AMERICA', 47, 10, 3, false, 1), 
       (545, 'UNKNOW', 'UNKNOW', 'LOCALIDAD', 'PUERTO RICO', 48, 10, 3, false, 1), 
       (546, 'UNKNOW', 'UNKNOW', 'LOCALIDAD', 'MONTECARLOS', 49, 10, 3, false, 1), 
       (547, 'UNKNOW', 'UNKNOW', 'LOCALIDAD', 'ANDRESITO', 50, 10, 3, false, 1), 
       (548, 'UNKNOW', 'UNKNOW', 'LOCALIDAD', 'ELDORADO', 51, 10, 3, false, 1), 
       (549, 'UNKNOW', 'UNKNOW', 'LOCALIDAD', 'CAMPO VIERA', 52, 10, 3, false, 1), 
       (550, 'UNKNOW', 'UNKNOW', 'LOCALIDAD', 'SANTA INES', 53, 10, 3, false, 1), 
       (551, 'UNKNOW', 'UNKNOW', 'LOCALIDAD', 'ALVEAR', 54, 10, 1, false, 1), 
       (552, 'UNKNOW', 'UNKNOW', 'LOCALIDAD', 'AZARA', 55, 10, 3, false, 1), 
       (553, 'UNKNOW', 'UNKNOW', 'LOCALIDAD', 'BONPLAND', 56, 10, 1, false, 1), 
       (554, 'UNKNOW', 'UNKNOW', 'LOCALIDAD', 'COLONIA GUARANI', 57, 10, 17, false, 1), 
       (555, 'UNKNOW', 'UNKNOW', 'LOCALIDAD', 'COLONIA LIEBIG', 58, 10, 4, false, 1), 
       (556, 'UNKNOW', 'UNKNOW', 'LOCALIDAD', 'CORPUS', 59, 10, 1, false, 1), 
       (557, 'UNKNOW', 'UNKNOW', 'LOCALIDAD', 'GDOR. VIRASORO', 60, 10, 4, false, 1), 
       (558, 'UNKNOW', 'UNKNOW', 'LOCALIDAD', 'H. IRIGOYEN', 61, 10, 1, false, 1), 
       (559, 'UNKNOW', 'UNKNOW', 'LOCALIDAD', 'ITUZAINGO', 62, 10, 4, false, 1), 
       (560, 'UNKNOW', 'UNKNOW', 'LOCALIDAD', 'LORETO', 63, 10, 1, false, 1), 
       (561, 'UNKNOW', 'UNKNOW', 'LOCALIDAD', 'OLEGARIO VICTOR ANDRADE', 64, 10, 1, false, 1), 
       (562, 'UNKNOW', 'UNKNOW', 'LOCALIDAD', 'PUERTO MADO', 65, 10, 1, false, 1), 
       (563, 'UNKNOW', 'UNKNOW', 'LOCALIDAD', 'PUERTO PIRAY', 66, 10, 1, false, 1), 
       (564, 'UNKNOW', 'UNKNOW', 'LOCALIDAD', 'SANTA RITA', 67, 10, 3, false, 1), 
       (565, 'UNKNOW', 'UNKNOW', 'LOCALIDAD', 'SANTO TOME', 68, 10, 4, false, 1), 
       (566, 'UNKNOW', 'UNKNOW', 'LOCALIDAD', 'PUERTO LEONI', 69, 10, 3, false, 1), 
       (567, 'UNKNOW', 'UNKNOW', 'LOCALIDAD', 'COLONIA VICTORIA', 70, 10, 3, false, 1), 
       (568, 'UNKNOW', 'UNKNOW', 'LOCALIDAD', 'PUERTO PANAMBI', 71, 10, 3, false, 1), 
       (569, 'UNKNOW', 'UNKNOW', 'LOCALIDAD', 'CONCORDIA', 72, 10, 5, false, 1), 
       (570, 'UNKNOW', 'UNKNOW', 'LOCALIDAD', 'COLONIA AURORA', 73, 10, 3, false, 1), 
       (571, 'UNKNOW', 'UNKNOW', 'LOCALIDAD', 'LANUS OESTE', 74, 10, 1, false, 1), 
       (572, 'UNKNOW', 'UNKNOW', 'LOCALIDAD', 'BARRACAS', 75, 10, 2, false, 1), 
       (573, 'UNKNOW', 'UNKNOW', 'LOCALIDAD', 'DOS HERMANAS', 76, 10, 3, false, 1), 
       (574, 'UNKNOW', 'UNKNOW', 'LOCALIDAD', 'SANTA FE', 77, 10, 15, false, 1), 
       (575, 'UNKNOW', 'UNKNOW', 'LOCALIDAD', 'MENDOZA', 78, 10, 17, false, 1);

