INSERT INTO parametro (id, usuarioalta, usuarioumod, clase, nombre, orden, tipo, version) VALUES ((35001), 'UNKNOW', 'UNKNOW', 'PROVINCIA', 'BUENOS AIRES', 1, 9, 1);
INSERT INTO parametro (id, usuarioalta, usuarioumod, clase, nombre, orden, tipo, version) VALUES ((35002), 'UNKNOW', 'UNKNOW', 'PROVINCIA', 'CAPITAL FEDERAL', 2, 9, 1);
INSERT INTO parametro (id, usuarioalta, usuarioumod, clase, nombre, orden, tipo, version) VALUES ((35003), 'UNKNOW', 'UNKNOW', 'PROVINCIA', 'CATAMARCA', 3, 9, 1);
INSERT INTO parametro (id, usuarioalta, usuarioumod, clase, nombre, orden, tipo, version) VALUES ((35004), 'UNKNOW', 'UNKNOW', 'PROVINCIA', 'CHACO', 4, 9, 1);
INSERT INTO parametro (id, usuarioalta, usuarioumod, clase, nombre, orden, tipo, version) VALUES ((35005), 'UNKNOW', 'UNKNOW', 'PROVINCIA', 'CHUBUT', 5, 9, 1);
INSERT INTO parametro (id, usuarioalta, usuarioumod, clase, nombre, orden, tipo, version) VALUES ((35006), 'UNKNOW', 'UNKNOW', 'PROVINCIA', 'CORDOBA', 6, 9, 1);
INSERT INTO parametro (id, usuarioalta, usuarioumod, clase, nombre, orden, tipo, version) VALUES ((35007), 'UNKNOW', 'UNKNOW', 'PROVINCIA', 'CORRIENTES', 7, 9, 1);
INSERT INTO parametro (id, usuarioalta, usuarioumod, clase, nombre, orden, tipo, version) VALUES ((35008), 'UNKNOW', 'UNKNOW', 'PROVINCIA', 'ENTRE RIOS', 8, 9, 1);
INSERT INTO parametro (id, usuarioalta, usuarioumod, clase, nombre, orden, tipo, version) VALUES ((35009), 'UNKNOW', 'UNKNOW', 'PROVINCIA', 'FORMOSA', 9, 9, 1);
INSERT INTO parametro (id, usuarioalta, usuarioumod, clase, nombre, orden, tipo, version) VALUES ((35010), 'UNKNOW', 'UNKNOW', 'PROVINCIA', 'JUJUY', 10, 9, 1);
INSERT INTO parametro (id, usuarioalta, usuarioumod, clase, nombre, orden, tipo, version) VALUES ((35011), 'UNKNOW', 'UNKNOW', 'PROVINCIA', 'LA PAMPA', 11, 9, 1);
INSERT INTO parametro (id, usuarioalta, usuarioumod, clase, nombre, orden, tipo, version) VALUES ((35012), 'UNKNOW', 'UNKNOW', 'PROVINCIA', 'LA RIOJA', 12, 9, 1);
INSERT INTO parametro (id, usuarioalta, usuarioumod, clase, nombre, orden, tipo, version) VALUES ((35013), 'UNKNOW', 'UNKNOW', 'PROVINCIA', 'MENDOZA', 13, 9, 1);
INSERT INTO parametro (id, usuarioalta, usuarioumod, clase, nombre, orden, tipo, version) VALUES ((35014), 'UNKNOW', 'UNKNOW', 'PROVINCIA', 'MISIONES', 14, 9, 1);
INSERT INTO parametro (id, usuarioalta, usuarioumod, clase, nombre, orden, tipo, version) VALUES ((35015), 'UNKNOW', 'UNKNOW', 'PROVINCIA', 'NEUQUN', 15, 9, 1);
INSERT INTO parametro (id, usuarioalta, usuarioumod, clase, nombre, orden, tipo, version) VALUES ((35016), 'UNKNOW', 'UNKNOW', 'PROVINCIA', 'RIO NEGRO', 16, 9, 1);
INSERT INTO parametro (id, usuarioalta, usuarioumod, clase, nombre, orden, tipo, version) VALUES ((35017), 'UNKNOW', 'UNKNOW', 'PROVINCIA', 'SALTA', 17, 9, 1);
INSERT INTO parametro (id, usuarioalta, usuarioumod, clase, nombre, orden, tipo, version) VALUES ((35018), 'UNKNOW', 'UNKNOW', 'PROVINCIA', 'SAN JUAN', 18, 9, 1);
INSERT INTO parametro (id, usuarioalta, usuarioumod, clase, nombre, orden, tipo, version) VALUES ((35019), 'UNKNOW', 'UNKNOW', 'PROVINCIA', 'SAN LUIS', 19, 9, 1);
INSERT INTO parametro (id, usuarioalta, usuarioumod, clase, nombre, orden, tipo, version) VALUES ((35020), 'UNKNOW', 'UNKNOW', 'PROVINCIA', 'SANTA CRUZ', 20, 9, 1);
INSERT INTO parametro (id, usuarioalta, usuarioumod, clase, nombre, orden, tipo, version) VALUES ((35021), 'UNKNOW', 'UNKNOW', 'PROVINCIA', 'SANTA FE', 21, 9, 1);
INSERT INTO parametro (id, usuarioalta, usuarioumod, clase, nombre, orden, tipo, version) VALUES ((35022), 'UNKNOW', 'UNKNOW', 'PROVINCIA', 'SANTIAGO DEL ESTERO', 22, 9, 1);
INSERT INTO parametro (id, usuarioalta, usuarioumod, clase, nombre, orden, tipo, version) VALUES ((35023), 'UNKNOW', 'UNKNOW', 'PROVINCIA', 'TIERRA DEL FUEGO', 23, 9, 1);
INSERT INTO parametro (id, usuarioalta, usuarioumod, clase, nombre, orden, tipo, version) VALUES ((35024), 'UNKNOW', 'UNKNOW', 'PROVINCIA', 'TUCUMAN', 24, 9, 1);
